#pragma config(Sensor, S1,     distance,       sensorEV3_Ultrasonic)
#pragma config(Sensor, S4,     color,          sensorEV3_Color, modeEV3Color_Color)
#pragma config(Motor,  motorA,          left,          tmotorEV3_Large, PIDControl, encoder)
#pragma config(Motor,  motorC,          claw,          tmotorEV3_Medium, PIDControl, encoder)
#pragma config(Motor,  motorD,          right,         tmotorEV3_Large, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int gState = 0;

void gState0()
{
	int cValue = 0;

	while(cValue == 0)
	{
		motor(left) = 20;
		motor(right) = 20;

		while(SensorValue(color) == colorBlack)
		{
			motor(left) = 30;
			motor(right) = 0;
		}
		while(sensorValue(color) == colorWhite)
		{
			motor(left) = 30;
			motor(right) = 15;
		}
			while(SensorValue(color) == colorBlack)
		{
			motor(left) = 0;
			motor(right) = 30;
		}
		while(sensorValue(color) == colorRed)
		{
			motor(left) = 30;
			motor(right) = 15;
		}
	}

}

void gState1()
{
	int leftBack;
	int rightBack;
	int goBack = 0;

	resetMotorEncoder(left);
	resetMotorEncoder(right);

	while((SensorValue(distance) > 4) && (goBack == 0))
	{
		motor(left) = 30;
		motor(right) = 30;
	}
	if((SensorValue(distance) <= 4) && (goBack == 0))
	{
		goBack = 1;
		motor(left) = 0;
		motor(right) = 0;
		leftBack = getMotorEncoder(left);
		rightBack = getMotorEncoder(right);
		resetMotorEncoder(left);
		resetMotorEncoder(right);
		motor(claw) = -30;
		wait1Msec(3900);
		motor(claw) = 0;
	}
	while((getMotorEncoder(left) > -leftBack) && (getMotorEncoder(right) > -rightBack))
	{
		motor(left) = -30;
		motor(right) = -30;
	}


	motor(left) = 0;
	motor(right) = 0;
	wait1Msec(100);

	resetMotorEncoder(left);
	resetMotorEncoder(right);

	while(getMotorEncoder(left) <= 360)
	{
		motor(left) = 20;
		motor(right) = -20;
	}

	motor(left) = 0;
	motor(right) = 0;

	motor(claw) = 30;
	wait1Msec(3900);
	motor(claw) = 0; //drop block

	resetMotorEncoder(left);
	resetMotorEncoder(right);

	while(getMotorEncoder(left) <= 360)
	{
		motor(left) = 20;
		motor(right) = -20;
	}

	motor(left) = 0;
	motor(right) = 0;

	gState = 2;

}

void gState2()
{
	motor(left) = 0;
	motor(right) = 0;

}

void gState3()
{
	while(SensorValue(color) == colorBlack)
	{
		motor(left) = 100;
		motor(right) = 100;
	}
	while(SensorValue(color) == colorWhite)
	{
		motor(left) = 0;
		motor(right) = 0;
	}
}

task main()
{

	//use methods for each gState

	while(gState == 0)
	{
		gState0();
		//position robot to travel to block a (assuming extra 4 pts for inital position)
	}

	resetMotorEncoder(left);
	resetMotorEncoder(right);

	while(gState == 1)
	{
		gState1();
		//travel to block a
		//retrieve block a
	}

	while(gState == 2)
	{
		motor(left) = 0;
		motor(right) = 0;
		gState2()
		//travel to block f
		//retrieve block f
	}

	while(gState == 3)
	{
		//return blacok f
	}

	while(gState == 4)
	{

		//game end

	}

}

//1, 6, 13
